### ISSUE TITLE
git submodules refer to non-existent URLs? and via ssh, not http

### ISSUE THREAD

**Issue by warner** [Agoric/playground-cosmos#2]
It looks like `.gitmodules` includes two modules at the very end, `evaluate` and `default-evaluate-options`, with URLs of `./evaluate` and `./default-evaluate-options`. This is failing when I do a `git submodule update --init` (see below). Neither is a real URL (unless we were keeping a whole git history in a subdirectory), and we don't seem to have a repository named `default-evaluate-options` anyways.

Also, I noticed that all the URLs in `.gitmodules` are of the form `git@github.com:Agoric/NAME`, which won't work for users who haven't set up an SSH key with Github. I'm thinking these should be `http://github.com/Agoric/NAME` instead. The downside is that when we (as committers in the submodules) want to push changes we made in-place, we'll need to do a `git remote add something git@github.com:Agoric/NAME`, or (better) pull those changes over into our normal checkout tree and prepare a PR from there.

```
warner@yoga:/tmp/t5$ git clone git@github.com:Agoric/playground-cosmos.git
Cloning into 'playground-cosmos'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 43 (delta 22), reused 35 (delta 14), pack-reused 0
Receiving objects: 100% (43/43), 51.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (22/22), done.
warner@yoga:/tmp/t5$ cd playground-cosmos
warner@yoga:/tmp/t5/playground-cosmos$ git submodule update --init
Submodule 'SES' (git@github.com:Agoric/SES) registered for path 'SES'
Submodule 'SwingSet' (git@github.com:Agoric/SwingSet) registered for path 'SwingSet'
Submodule 'acorn-infix-bang' (git@github.com:Agoric/acorn-infix-bang) registered for path 'acorn-infix-bang'
Submodule 'cosmic-swingset' (git@github.com:Agoric/cosmic-swingset) registered for path 'cosmic-swingset'
Submodule 'default-evaluate-options' (git@github.com:Agoric/playground-cosmos.git/default-evaluate-options) registered for path 'default-evaluate-options'
Submodule 'ertp' (git@github.com:Agoric/ERTP) registered for path 'ertp'
Submodule 'evaluate' (git@github.com:Agoric/playground-cosmos.git/evaluate) registered for path 'evaluate'
Submodule 'eventual-send' (git@github.com:Agoric/eventual-send) registered for path 'eventual-send'
Submodule 'harden' (git@github.com:Agoric/harden) registered for path 'harden'
Submodule 'make-hardener' (git@github.com:Agoric/make-hardener) registered for path 'make-hardener'
Submodule 'marshal' (git@github.com:Agoric/marshal) registered for path 'marshal'
Submodule 'nat' (git@github.com:Agoric/nat) registered for path 'nat'
Submodule 'transform-bang' (git@github.com:Agoric/transform-bang) registered for path 'transform-bang'
Cloning into '/tmp/t5/playground-cosmos/SES'...
Cloning into '/tmp/t5/playground-cosmos/SwingSet'...
Cloning into '/tmp/t5/playground-cosmos/acorn-infix-bang'...
Cloning into '/tmp/t5/playground-cosmos/cosmic-swingset'...
Cloning into '/tmp/t5/playground-cosmos/default-evaluate-options'...
fatal: remote error: 
  Agoric/playground-cosmos.git/default-evaluate-options is not a valid repository name
  Email support@github.com for help
fatal: clone of 'git@github.com:Agoric/playground-cosmos.git/default-evaluate-options' into submodule path '/tmp/t5/playground-cosmos/default-evaluate-options' failed
Failed to clone 'default-evaluate-options'. Retry scheduled
Cloning into '/tmp/t5/playground-cosmos/ertp'...
Cloning into '/tmp/t5/playground-cosmos/evaluate'...
fatal: remote error: 
  Agoric/playground-cosmos.git/evaluate is not a valid repository name
  Email support@github.com for help
fatal: clone of 'git@github.com:Agoric/playground-cosmos.git/evaluate' into submodule path '/tmp/t5/playground-cosmos/evaluate' failed
Failed to clone 'evaluate'. Retry scheduled
Cloning into '/tmp/t5/playground-cosmos/eventual-send'...
Cloning into '/tmp/t5/playground-cosmos/harden'...
Cloning into '/tmp/t5/playground-cosmos/make-hardener'...
Cloning into '/tmp/t5/playground-cosmos/marshal'...
Cloning into '/tmp/t5/playground-cosmos/nat'...
Cloning into '/tmp/t5/playground-cosmos/transform-bang'...
Cloning into '/tmp/t5/playground-cosmos/default-evaluate-options'...
fatal: remote error: 
  Agoric/playground-cosmos.git/default-evaluate-options is not a valid repository name
  Email support@github.com for help
fatal: clone of 'git@github.com:Agoric/playground-cosmos.git/default-evaluate-options' into submodule path '/tmp/t5/playground-cosmos/default-evaluate-options' failed
Failed to clone 'default-evaluate-options' a second time, aborting
```

**Comment by warner** [comment]
When I remove `default-evaluate-options` and fix the URL for `evaluate`, my submodule-update then fails because the ERTP submodule spec refers to a commit id that doesn't exist:

```
warner@yoga:/tmp/t5/playground-cosmos$ git submodule update --init
Submodule 'ertp' (git@github.com:Agoric/ERTP) registered for path 'ertp'
Submodule 'evaluate' (git@github.com:Agoric/evaluate) registered for path 'evaluate'
Submodule 'eventual-send' (git@github.com:Agoric/eventual-send) registered for path 'eventual-send'
Submodule 'harden' (git@github.com:Agoric/harden) registered for path 'harden'
Submodule 'make-hardener' (git@github.com:Agoric/make-hardener) registered for path 'make-hardener'
Submodule 'marshal' (git@github.com:Agoric/marshal) registered for path 'marshal'
Submodule 'nat' (git@github.com:Agoric/nat) registered for path 'nat'
Submodule 'transform-bang' (git@github.com:Agoric/transform-bang) registered for path 'transform-bang'
Cloning into '/tmp/t5/playground-cosmos/SES'...
Cloning into '/tmp/t5/playground-cosmos/SwingSet'...
Cloning into '/tmp/t5/playground-cosmos/acorn-infix-bang'...
Cloning into '/tmp/t5/playground-cosmos/cosmic-swingset'...
Cloning into '/tmp/t5/playground-cosmos/ertp'...
Cloning into '/tmp/t5/playground-cosmos/evaluate'...
Cloning into '/tmp/t5/playground-cosmos/eventual-send'...
Cloning into '/tmp/t5/playground-cosmos/harden'...
Cloning into '/tmp/t5/playground-cosmos/make-hardener'...
Cloning into '/tmp/t5/playground-cosmos/marshal'...
Cloning into '/tmp/t5/playground-cosmos/nat'...
Cloning into '/tmp/t5/playground-cosmos/transform-bang'...
Submodule path 'SES': checked out '21306b42cb53a8283c325c12af784c842895b4c8'
Submodule path 'SwingSet': checked out '1920196833e925fb974e29df0921d7bea9586615'
Submodule path 'acorn-infix-bang': checked out 'd93789466399f5bae88cf7e9492a61a93559b463'
Submodule path 'cosmic-swingset': checked out 'e9692a1919c8797fac437279c6ede49f5d3e6e26'
Fetched in submodule path 'ertp', but it did not contain 36ef7da0c6ec0111aa2d3c37812c2b3cea4451e1. Direct fetching of that commit failed.
```

Was this referring to a branch of ERTP that got pruned? Or did trunk get force-pushed after the commit ID was added to playground-cosmos?

**Comment by michaelfig** [comment]
Oops, my oversight.  I've fixed this now.  Please pull from master.

Note that overriding the submodule URL can be done by editing the `.git/config` submodule `url` entries after `git submodule init` (but before `git submodule update`), no need to mess with remotes.

**Comment by warner** [comment]
Looks better.. although `default-evaluate-options` still doesn't exist. When we use http instead of ssh, git assumes it can't see the repo because it doesn't have permission, so it asks for a username+password instead of just failing immediately, which is confusing in a different way :).

**Comment by michaelfig** [comment]
Wow, did I ever get that wrong!  I had to rename `transform-default` to `default-evaluate-options` and now it seems to work.

An integration test would be nice.

**Comment by warner** [comment]
Cool, submodule update works for me now. I'll file separate issues for the next error I see. Thanks!
